@startuml AC
left to right direction

mainframe **ac** Smart Lock
actor :Bruger: as user
actor :Administrator: as admin
actor :Lås på dør: as lock

rectangle "\n**Smart Lock**\n\n\n" {
    
}

user -- "\n**Smart Lock**\n\n\n"
"\n**Smart Lock**\n\n\n" -- lock
admin -- "\n**Smart Lock**\n\n\n"


@enduml