@startuml UC
left to right direction

mainframe **uc** Smart Lock
actor :Bruger: as user
actor :Administrator: as admin
actor :Lås på dør: as lock

rectangle "Smart Lock" {
    usecase (1. Lås døren op) as (unlock)
    usecase (2. Tilføj bruger) as (add)
    usecase (3. Rediger bruger) as (edit)
    usecase (4. Hent logs) as (logs)
    usecase (5. Slet bruger) as (delete)
}

user -- (unlock)
(unlock) -- lock
admin -- (add)
admin -- (edit)
admin -- (logs)
admin -- (delete)


@enduml
